inputs:
  name:
    description: "Download libtorch"
runs:
  using: "composite"
  steps:
    - name: Download libtorch
      run: |
        wget "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.11.0%2Bcpu.zip"
        echo "5b5ea3067f878dea051f6fcd8fb00338f55517cb6baecdc810983a814e030845 libtorch-cxx11-abi-shared-with-deps-1.11.0+cpu.zip" | sha256sum -c -
        unzip libtorch-cxx11-abi-shared-with-deps-1.11.0+cpu.zip
        echo "LIBTORCH=$(realpath libtorch)" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(realpath libtorch)/lib" >> $GITHUB_ENV
      shell: bash
