name: 'syntaxdot-libtorch'
description: "Download libtorch"

inputs:
  device:
    description: "Device build"
    default: "cpu"
runs:
  using: "composite"
  steps:
    - name: Download libtorch
      run: |
        wget "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.1.0%2Bcpu.zip"
        echo "04f699d5181048b0062ef52de1df44b46859b8fbeeee12abdbcb9aac63e2a14b libtorch-cxx11-abi-shared-with-deps-2.1.0+cpu.zip" | sha256sum -c -
        unzip libtorch-cxx11-abi-shared-with-deps-2.1.0+cpu.zip
        echo "LIBTORCH=$(realpath libtorch)" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(realpath libtorch)/lib" >> $GITHUB_ENV
        rm libtorch-cxx11-abi-shared-with-deps-2.1.0+cpu.zip
      shell: bash
      if: ${{ inputs.device == 'cpu' }}
    - name: Download libtorch (CUDA)
      run: |
        wget "https://download.pytorch.org/libtorch/cu121/libtorch-cxx11-abi-shared-with-deps-2.1.0%2Bcu121.zip"
        echo "fc1afc2fb28e2ab7b526df04c574c173fc6f068b5fbca831734607ef39fd6893 libtorch-cxx11-abi-shared-with-deps-2.1.0%2Bcu121.zip" | sha256sum -c -
        unzip libtorch-cxx11-abi-shared-with-deps-2.1.0%2Bcu121.zip
        echo "LIBTORCH=$(realpath libtorch)" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(realpath libtorch)/lib" >> $GITHUB_ENV
        rm libtorch-cxx11-abi-shared-with-deps-2.1.0%2Bcu121.zip
      shell: bash
      if: ${{ inputs.device == 'cuda' }}
