name: 'syntaxdot-libtorch'
description: "Download libtorch"

inputs:
  device:
    description: "Device build"
    default: "cpu"
runs:
  using: "composite"
  steps:
    - name: Download libtorch
      run: |
        wget "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.0.0%2Bcpu.zip"
        echo "2d67cff381186f2a01140348d2da7ab35d2e526c5703f4a8312c9428bef6df88 libtorch-cxx11-abi-shared-with-deps-2.0.0+cpu.zip" | sha256sum -c -
        unzip libtorch-cxx11-abi-shared-with-deps-2.0.0+cpu.zip
        echo "LIBTORCH=$(realpath libtorch)" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(realpath libtorch)/lib" >> $GITHUB_ENV
        rm libtorch-cxx11-abi-shared-with-deps-2.0.0+cpu.zip
      shell: bash
      if: ${{ inputs.device == 'cpu' }}
    - name: Download libtorch (CUDA)
      run: |
        wget "https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.0.0%2Bcu118.zip"
        echo "292b3f81e7c857fc102be93e2e44c40cdb4d8ef03d98121bc6af434c66e8490b libtorch-cxx11-abi-shared-with-deps-2.0.0+cu118.zip" | sha256sum -c -
        unzip libtorch-cxx11-abi-shared-with-deps-2.0.0+cu118.zip
        echo "LIBTORCH=$(realpath libtorch)" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(realpath libtorch)/lib" >> $GITHUB_ENV
        rm libtorch-cxx11-abi-shared-with-deps-2.0.0+cu118.zip
      shell: bash
      if: ${{ inputs.device == 'cuda' }}
