inputs:
  name:
    description: "Download libtorch"
runs:
  using: "composite"
  steps:
    - name: Download libtorch
      run: |
        wget "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.13.0%2Bcpu.zip"
        echo "d52f63577a07adb0bfd6d77c90f7da21896e94f71eb7dcd55ed7835ccb3b2b59 libtorch-cxx11-abi-shared-with-deps-1.13.0+cpu.zip" | sha256sum -c -
        unzip libtorch-cxx11-abi-shared-with-deps-1.13.0+cpu.zip
        echo "LIBTORCH=$(realpath libtorch)" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(realpath libtorch)/lib" >> $GITHUB_ENV
      shell: bash
