inputs:
  name:
    description: "Download libtorch"
runs:
  using: "composite"
  steps:
    - name: Download libtorch
      run: |
        wget "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.10.0%2Bcpu.zip"
        echo "6d7be1073d1bd76f6563572b2aa5548ad51d5bc241d6895e3181b7dc25554426 libtorch-cxx11-abi-shared-with-deps-1.10.0+cpu.zip" | sha256sum -c -
        unzip libtorch-cxx11-abi-shared-with-deps-1.10.0+cpu.zip
        echo "LIBTORCH=$(realpath libtorch)" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$(realpath libtorch)/lib" >> $GITHUB_ENV
      shell: bash
